# Configuración global de eventos
events {
}

# Configuración del servidor web
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;

        server_name localhost;

        # Configuración del directorio raíz y archivo índice
        root /usr/share/nginx/html;
        index index.csr.html;

        # Manejo de rutas de Angular (para el enrutamiento basado en el cliente)
        location / {
            try_files $uri $uri/ /index.csr.html;  # redireccionar al index
        }
        
        error_page 404 /index.csr.html;

        error_page 403 /403.html;

        location = /403.html {
            root /usr/share/nginx/html;
        }

    }
}